version: '3.8'

services:
  app:
    build: .
    container_name: php74_app
    ports:
      - "8080:80"
    volumes:
      - /Volumes/Rian/PHP/BACKEND_ARSIP:/var/www/html  # Mount full path
      - /Volumes/Rian/PHP/BACKEND_ARSIP/api_sudikap_laravel/.env:/var/www/html/api_sudikap_laravel/.env
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "3000:8080"
    depends_on:
      - db

volumes:
  db_data: